name: Simulate Earthquake Every 1 Minute

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Run simulator script
        run: python simulate_quake_generator.py

      - name: Commit changes
        run: |
          git add quake.json
          git commit -m "Update quake.json"
        continue-on-error: true  # กันไว้ถ้าไม่มีอะไรเปลี่ยน

      - name: Pull latest changes (rebase)
        run: |
          git pull --rebase origin main
        continue-on-error: true  # กันไว้กรณี conflict หรือไม่มีอะไรใหม่

      - name: Push changes back to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
